### PR TITLE
Run attack command line using target json and config json

### PR DESCRIPTION
**Pull request by shahzadmumtaz22**
- Enhanced functionality of running LIRA and Worstcase attack from the command line using saved target (target.json) and configuration files
- Examples updated
- Related tests updated

### CODE REVIEW

**Comment by rpreen** [comment]
I think we need this for the attribute attack as well?

**Comment by rpreen** [comment]
I wonder if we need a main entry point so one attack_config.json can fire multiple attacks?

**Comment by shahzadmumtaz22** [comment]
> I think we need this for the attribute attack as well?

@rpreen 
Yes, I agree that we also need this for the attribute attack. I plan to make a separate PR for this.

**Comment by shahzadmumtaz22** [comment]
> I wonder if we need a main entry point so one attack_config.json can fire multiple attacks?

@rpreen 

Yes, I have a plan to initiate a separate PR for a single entry point so we can run multiple attacks using a single configuration file and a target save model.

**Review by rpreen — APPROVED** [review]

**Pull request merged**
