### PR TITLE
fixing the json file produced by safemodels

### PR DESCRIPTION
**Pull request by mahaalbashir**

### CODE REVIEW

**Comment by mahaalbashir** [comment]
@rpreen can you please help me find out why the tests are failing?

**Comment by jim-smith** [comment]
Yes,
I have some memories that we had to go through a few hoops making sure that the outputs from different types of classifiers was serialisable.

**Comment by simonrnss** [comment]
@shahzadmumtaz22 you might need to write something extra into the json encoder, depending on what the object is that is causing the issue

**Comment by jim-smith** [comment]
@rpreen Think this is ready to be approved and merged

**Pull request merged**
