### PR TITLE
DRAFT: 30 programmatic attack running

### LINKED ISSUE #30: Programmatic attack running
Both MIA attack types should adhere to the same interface and produce output in the same format. This will mean that they can be called from within the wrappers easily.

Decision for initial discussions:
1. Attacks should use dataset class (see attack_utils in GM repo)
2. Superclass for all attacks should be defined (not clear atm how much functionality will go in here)
3. SR to make WorstCase and LiRa code conform to this and then RP will do the same for AIA
4. Some work will be needed on aligning output but this can wait until all attacks have been implemented

@jim-smith , @rpreen , @albacrespi -- does this match your recollection (sorry I had to disappear so quick -- home office sharer had job interview)

### PR DESCRIPTION
**Pull request by simonrnss**
Closes #30

- [X] Refactor worst_case_attack.py
- [X] Create attack superclass
- [X] Make worst case example compatible
- [x] Verify that this can be called successfully from the wrappers
- [x] Refactor likelihood_attack.py
- [x] Add AIA attack class

### CODE REVIEW

**Comment by rpreen** [comment]
Looking at the example, the attacks don't seem to be receiving any information about the features and their encoding - it's only receiving the encoded train/test arrays. For attribute inference we'll need at least information about the indices and the encoding method. Something like adding to the Data class:

```python
    def add_feature(self, name: str, indices: list[int], encoding: str) -> None:
        """Adds a feature description to the data dictionary."""
        index: int = len(self.features)
        self.features[index] = {
            "name": name,
            "indices": indices,
            "encoding": encoding,
        }
```

And then for example the information can be added something like:
```python
        indices: list[list[int]] = [
            [0, 1, 2],  # parents
            [3, 4, 5, 6, 7],  # has_nurs
            [8, 9, 10, 11],  # form
            [12, 13, 14, 15],  # children
            [16, 17, 18],  # housing
            [19, 20],  # finance
            [21, 22, 23],  # social
            [24, 25, 26],  # health
        ]

        dataset_obj = dataset.Data()
        dataset_obj.add_processed_data(train_X, train_y, test_X, test_y)
        for i in range(self.n_features):
            dataset_obj.add_feature(data.feature_names[i], indices[i], "onehot")
```

or

```python
        indices: list[list[int]] = []
        for i in range(self.n_features):
            indices.append([i])

        dataset_obj = dataset.Data()
        dataset_obj.add_processed_data(train_X, train_y, test_X, test_y)
        for i in range(self.n_features):
            dataset_obj.add_feature(self.data.columns[i], indices[i], str(self.data.dtypes[i]))

**Comment by simonrnss** [comment]
> Looking at the example, the attacks don't seem to be receiving any information about the features and their encoding - it's only receiving the encoded train/test arrays. For attribute inference we'll need at least information about the indices and the encoding method. Something like adding to the Data class:
> 
> ```python
>     def add_feature(self, name: str, indices: list[int], encoding: str) -> None:
>         """Adds a feature description to the data dictionary."""
>         index: int = len(self.features)
>         self.features[index] = {
>             "name": name,
>             "indices": indices,
>             "encoding": encoding,
>         }
> ```
> 
> And then for example the information can be added something like:
> 
> ```python
>         indices: list[list[int]] = [
>             [0, 1, 2],  # parents
>             [3, 4, 5, 6, 7],  # has_nurs
>             [8, 9, 10, 11],  # form
>             [12, 13, 14, 15],  # children
>             [16, 17, 18],  # housing
>             [19, 20],  # finance
>             [21, 22, 23],  # social
>             [24, 25, 26],  # health
>         ]
> 
>         dataset_obj = dataset.Data()
>         dataset_obj.add_processed_data(train_X, train_y, test_X, test_y)
>         for i in range(self.n_features):
>             dataset_obj.add_feature(data.feature_names[i], indices[i], "onehot")
> ```
> 
> or
> 
> ```python
>         indices: list[list[int]] = []
>         for i in range(self.n_features):
>             indices.append([i])
> 
>         dataset_obj = dataset.Data()
>         dataset_obj.add_processed_data(train_X, train_y, test_X, test_y)
>         for i in range(self.n_features):
>             dataset_obj.add_feature(self.data.columns[i], indices[i], str(self.data.dtypes[i]))
> ```

Yes, thanks -- I was hoping you'd add this back when the attribute inference attacks are put into this format. The MIAs don't need that information so I only copied things from the dataset class that I was going to use. We may well need everything that was in the original, which is fine.

**Comment by jim-smith** [comment]
wrapper method added to allow calling attacks - only worst_case implemented as yet

See question under related issue about whether we should force users to submit their Data object as a parameter when they call request_release() because I **really** don't want it saved anywhere near the safemodel wrapper object

**Comment by simonrnss** [comment]
@mccarthyajb and @jim-smith -- are you happy for me to work on the other attack type with the same structure?

**Comment by simonrnss** [comment]
Hi all -- I've refactored both MIA attacks now. I need to properly comment the newly refactored LIRA code. But you should be able to call it in exactly the same way as the WorstCase. I.e.
```python
from attacks.likelihood_attck import LIRAAttackArgs, LIRAAttack
attack_obj = LIRAAttack(LIRAAttackArgs(n_shadow_models=50))

# or attack_obj = LIRAAttack() if no changes from default args
attack_obj.attack(dataset, target_model)
output = attack_obj.make_report() # also produces .pdf and .json if the report_name argument is set
```

Over to you guys for the AIA version

**Comment by jim-smith** [comment]
@simonrnss edited your likelihood_attack.py to put in some explicit casts to ints. 4-5 places I think, they were barfing at run time.
-I've marked them with comments with my name in so you can see them.

**Comment by simonrnss** [comment]
> @simonrnss edited your likelihood_attack.py to put in some explicit casts to ints. 4-5 places I think, they were barfing at run time. -I've marked them with comments with my name in so you can see them.

Hi @jim-smith -- great. I modified a little....moved the casting into the `attacks.dataset.Data` class when `add_processed_data` is called. I think it's marginally neater to cast them at source. Let me know if that doesn't stop the warnings...

**Comment by jim-smith** [comment]
Hi @simonrnss good idea about movingthex casting- certainly where I put it was only a temporary fix :)

Just tested the new version runs fine with one of the scripts I added to examples and it runs fine, whereas it threw exceptions and exited in an ungainly fashion without the casts

**Comment by jim-smith** [comment]
@simonrnss is it a problem that lira won't work for keras models because it does sklearn.base.clone()

**Comment by simonrnss** [comment]
This is because we want to make a shadow model that is identical to the target model (all hyper-params etc). Does keras have an alternative?

**Comment by jim-smith** [comment]
https://www.tensorflow.org/api_docs/python/tf/keras/models/clone_model
not an alternative,
 so you would need to check the base type of the model before deciding which cloning code to use

**Comment by simonrnss** [comment]
That's annoying -- the problem would go away if we only accepted our own model class, in which a clone method has to be implemented....or, the code has to be passed the untrained shadow model as well as the trained target model...?

**Comment by simonrnss** [comment]
@jim-smith how about the following solution....when users call attack, we include the untrained shadow model as an optional argument with default value of `None`. If the user doesn't set this, it tries the sklearn clone method. If that fails, we catch the exception and report to the user that for non sklearn models, the user needs to supply the untrained shadow model?

Out of interest, does the sklearn clone method work on your safemodel class?

**Comment by simonrnss** [comment]
ah, sorry, not thinking straight. We can check the base class and use one or other of those, and sqwark if the model isn't either

**Comment by simonrnss** [comment]
gah - still talking nonsense.
There are other reasons why it won't accept keras at the moment. These are that it relies upon `predict_proba` and `fit`, neither of which will work if the model isn't a sklearn-style model.
I therefore propose we "don't support keras at this time"

**Comment by jim-smith** [comment]
@simonrnss 
>>Out of interest, does the sklearn clone method work on your safemodel class?
well, I had to do some rewriting of the super class and all the derived classes, but after a couple of hours I figured I just needed to:
- add a list of expected parameter names in each classes constructor
-  and only pass them to the sklearn/keras constructor in __init__ 
- -and use that list to implement a new version of get_params()
After than it works fine ...

>There are other reasons why it won't accept keras at the moment. These are that it relies upon predict_proba and fit, >neither of which will work if the model isn't a sklearn-style model.
>I therefore propose we "don't support keras at this time"

Ok, but it shouldn't;t be that hard to do for a release in the near future

- keras supports fit() - as does safekeras because we overwrite it
- -  sequential keras models support predict_proba
- in general since '''model.outputs is the list of output tensors.''' you can get at the outputs , hence  predict_proba

**Comment by rpreen** [comment]
Seems like the attribute inference attack is integrated. Can someone please check that the example works?
`$ python -m examples.attribute_inference_example`

Btw, I refuse to fix the remaining pylint warnings because it's using python 3.8 and here in the present day 3.10 pylint is happy.

**Comment by simonrnss** [comment]
Thanks @rpreen 
Just ran the code and I think it works....however,
1. I get loads of runtime warnings (pasted below)
2. It seems to be looping repeatedly. According to the example, it should run once, but it's now been running for a long time, repeating the same output over and over again. This looks like an issue with multiprocessing (which I installed and added to requirements). I'm running windows (not through choice), which might not be helping. I wonder if we can make the use of multiprocess optional?
3. The linting issue -- we do need to do something about this I think. The issue is that in py3.8 there are not built-in list (dict, etc) types. In other parts of the code we are importing List, Dict, etc from typing. I think we should either move to 3.10 and use the built-in types _throughout_, or stick in 3.8 and use the imported ones _throughout_. I don't think we should mix and match.

Here's the multiprocess error:

Base model train accuracy: 1.0
Base model test accuracy: 0.9862654320987654
Base model train accuracy: 1.0
Base model test accuracy: 0.9868827160493827
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\spawn.py", line 234, in prepare
    _fixup_main_from_name(data['init_main_from_name'])
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\spawn.py", line 258, in _fixup_main_from_name
    main_content = runpy.run_module(mod_name,
  File "c:\users\simonr04\appdata\local\programs\python\python39\lib\runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "c:\users\simonr04\appdata\local\programs\python\python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\users\simonr04\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\simonr04\git\AI-SDC\examples\attribute_inference_example.py", line 87, in <module>
    attack_obj.attack(data, model)
  File "C:\Users\simonr04\git\AI-SDC\attacks\attribute_attack.py", line 72, in attack
    self.attack_metrics = _attribute_inference(
  File "C:\Users\simonr04\git\AI-SDC\attacks\attribute_attack.py", line 519, in _attribute_inference
    results_a: list[dict] = _attack_brute_force(
  File "C:\Users\simonr04\git\AI-SDC\attacks\attribute_attack.py", line 366, in _attack_brute_force
    with mp.Pool(processes=n_cpu) as pool:
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\simonr04\git\AI-SDC\venv\lib\site-packages\multiprocess\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by rpreen** [comment]
It does take a little while to run: about 2m50s on my laptop because it is an intensive search.

It will repeat the same process a number of times for each feature on both train and test tests. If you add the following to line 22 in `attacks/attribute_attack.py` it will display much more information that might help.
```python
logger.setLevel(logging.DEBUG)
```

I'm not sure what to think about the warnings yet.

I agree that we should go with one typing standard, but my preference would be for 3.10 since that's the current stable version and it's clearly the method going forward to have most of these as built-in types; it's also backwards compatible immediately so just by switching to 3.10 it doesn't force an immediate upgrade of the old types.

**Comment by simonrnss** [comment]
I stopped it after about 10 mins, so don't think it was quite right?

Happy to go py3.10. I'll make an issue to bump it up in requirements, the pylint action and modify the typing in the rest of the code. Hopefully will be able to sort that today (will make a branch off 30 to avoid any conflicts)

**Comment by simonrnss** [comment]
nice, thanks!

**Comment by rpreen** [comment]
I just ran it in my Windows VM and i'm seeing the same loop-warning apocalypse, so something is definitely broken on Windows.

**Comment by jim-smith** [comment]
@simonrnss @rpreen After initially hanging everything else for about 30s it then seems to run ok on my MacBook.
 But I've got 8 cores and I notice that you hard code using 8 cores into your example

> attack_args = attribute_attack.AttributeAttackArgs(n_cpu=8)

could you get that programmatically and leave one free for the user/os?
that might fix the problem on windows too without having to put in extra code that behaves differently on windows (yuk)

Then I guess the next step is to edit safemodel.safemode.py to:
 import your attack code and 
(ii) in the class method run_attack()  call your  attack rather than just returning a 'not implemented' string

**Comment by rpreen** [comment]
The default is to automatically select all CPU cores (if no n_cpu param is passed), but I thought for the example I would add the parameter to show how it can be controlled.

**Comment by jim-smith** [comment]
All cpu cores seems a little unfriendly to the user :) 
Suggest changing the example to 7 (and putting in a comment suggesting people change this to 3 if they have 4 cores)

Could we change the default to max 1: n_cpu -1 ?

**Comment by jim-smith** [comment]
@rpreen let me know if it not obvious how to change safemodel.py

**Comment by rpreen** [comment]
I've added the attribute attack to safemodel in the way that looks sensible, but I don't have a way to test it.

Also, I'm not sure the AIA output format/report is exactly what we want, but at least it's in for now.

**Comment by jim-smith** [comment]
test integration using:

python -m examples.safemodel_attack_integration_runattack
python -m examples.safemodel_attack_integration_request_release

that will run all three or you can edit the first script to sit call attribute attacks during testing.

When I pulled the latest version of this branch and ran it, it produces two png's but leaves the lists and json empty.
maybe populate those lists with: the json equivalent of a table containing 
Attribute name
train risk
test risk
attribute. risk ratio

**Comment by jim-smith** [comment]
@rpreen @simonrnss pushed a new version of the script that creates a safemodel then calls run attack on it for each type of attack in turn.
It now runs ok with the attribute inference but failed with an index error for lira:
>  File "/Users/j4-smith/Documents/AI-SDC/attacks/likelihood_attack.py", line 242, in run_scenario_from_preds
    confidences[i, y_target_train[i]]
IndexError: index 4 is out of bounds for axis 1 with size 4

Does this dataset (nursery) have classes 1-4 but lira assumes 0-3?

**Comment by rpreen** [comment]
I don't know, but you don't have an if statement checking for main in that example code so it will likely :boom: on Windows

**Comment by rpreen** [comment]
I think there are 5 classes in the y labels according to [openml](https://www.openml.org/search?type=data&status=active&id=26&sort=runs)

**Comment by jim-smith** [comment]
@rpreen updated scripts to include main and convert nursery to a two class problem.
-can you check the output from attribute inference is what you would expect please 
@simonrnss  is it right that LIRA maybe only works for two-class problems

**Comment by jim-smith** [comment]
@simonrnss - yes it had just 2 examples,
I've relabelled those in the scripts for the sake of passing tests , but maybe we should raise an issue to make the lira attack code look at both y_train and y_test to determine the size of the array?

**Comment by simonrnss** [comment]
Perhaps just removing any rows from the test set that belong to classes not represented in the training set?
Also, I realise now for multi-class that I need to be careful in the lira code. I use the class to index into the probabilities, but there's no guarantee that class n will be in column n. I'll raise an issue to address both things...

**Comment by jim-smith** [comment]
@simonrnss @rpreen 
for now I think the two scripts work fine,

@rpreen is the output what you would expect for the attribute inference attacks?   
if it is then please agree the pull requisition and merge.

**Comment by rpreen** [comment]
The output is what I expect, but I can improve it. I'll try and mimic the json/pdf stuff from Simon's `make_report()` so it's more consistent.

**Comment by simonrnss** [comment]
Also, please don't merge until I've done the py310 stuff. Just about to start.
And...can you take a quick look at the code duplication thing that pylint is pulling out? It's quite a big chunk. We can add an explicit ignore if it's ok to have it in both places.

**Review by jim-smith — APPROVED** [review]

**Comment by simonrnss** [comment]
@rpreen -- I think you're working on this branch, so will leave you to approve #43 which will merge the python 3.10 changes into _this_ branch. It's ready to merge now (the pylint things can all be addressed in this branch, instead of this one)

**Comment by jim-smith** [comment]
@simonrnss 
>And...can you take a quick look at the code duplication thing that pylint is pulling out? It's quite a big chunk. 
>We can add an explicit ignore if it's ok to have it in both places.

its just illustrating two different ways of calling the automated test, so yes there is lots of duplicated code.
I originally had it all in one file, but for some reason it throws wobblies around objects of type int64 not being serialisable  that disappear way when I put the code into two files.   
No idea what the issue is, but don't thing it does any harm to have two examples

**Comment by simonrnss** [comment]
Ok -- I'll tell pylint to shuttup about that one.

re the int64, are you calling json.dumps somewhere? If so, change the line to: `json.dumps(..., cls=report.NumpyArrayEncoder)` with a `from attacks import report` at the top.

**Comment by jim-smith** [comment]
@simonrss the new combined script runs ok on my machine and works with ther really tiny class so  looks like your LIRA fixes have worked.
I don't understand why it fails pylint - it gets 10/10 t hen the process exits with status 8

**Comment by jim-smith** [comment]
@rpreen @simonrnss I think it is just tidying up to do now? 
I need to do other things for the rest of the afternoon

**Comment by jim-smith** [comment]
@simonrnss 
bother, actually there is still a serious problem with the LIRA code

I misunderstood and thought that Simon had already put the new lira into this branch

I've fixed some typos in the ne version of  the lira attack 
- line 130, np.npdarray => np.ndarray
-  _classes => 'classes_

And I've checked that the dataset changing code seems to be ok, but I'm still seeing od things with some splits:
```
INFO:lr-scenario:Training shadow models
INFO:lr-scenario:Trained 0 models
shadow clf returned confidences with shape (6480, 5)
shadow clf returned confidences with shape (6480, 5)
shadow clf returned confidences with shape (6480, 5)
shadow clf returned confidences with shape (6480, 5)
shadow clf returned confidences with shape (6480, 4)
Traceback (most recent call last):
  File "/Users/j4-smith/miniforge3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/j4-smith/miniforge3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/j4-smith/Documents/AI-SDC/examples/safemodel_attack_integration_bothcalls.py", line 87, in <module>
    metadata= model.run_attack(the_data,attack_name,fname)
  File "/Users/j4-smith/Documents/AI-SDC/safemodel/safemodel.py", line 819, in run_attack
    attack_obj.attack(data_obj,self)
  File "/Users/j4-smith/Documents/AI-SDC/attacks/likelihood_attack.py", line 117, in attack
    self.run_scenario_from_preds(
  File "/Users/j4-smith/Documents/AI-SDC/attacks/likelihood_attack.py", line 282, in run_scenario_from_preds
    confidences[i, y_target_train[i]]
IndexError: index 4 is out of bounds for axis 1 with size 4
```


and it is because these liens of code still do random sampling
```python
      for model_idx in range(self.args.n_shadow_models):
            if model_idx % 10 == 0:
                logger.info("Trained %d models", model_idx)
            # Pick the indices to use for training this one
            np.random.seed(model_idx) # Reproducibility
            these_idx = np.random.choice(indices, n_train_rows, replace=False)
            temp_X_train = combined_X_train[these_idx, :]
            temp_y_train = combined_y_train[these_idx]
```

and whatever we do, if they choose a training set without the small fifth class in, then that shadow model is going to learn 4 classes.  
So either:
- each of these repetitions needs to do the dataset shifting thing again, 
or. 
- maybe it could call a stratified train/test split instead of just doing a random selection of indices

**Comment by simonrnss** [comment]
ah, yes, of course. I can fix that.

**Comment by simonrnss** [comment]
Fixed I think -- please test (in branch 30). If we get a split that leaves a class unrepresented in the training side, then the confidence for the test point is zero (by definition). It has zero probability of being in the correct class.

**Comment by jim-smith** [comment]
@simonrnss this is the output form the run I just did with the fixes to your code: 
  TPR: 0.7895
               FPR: 0.9779
               FAR: 0.5533
               TNR: 0.0221
               PPV: 0.4467
               NPV: 0.0949
               FNR: 0.2105
               ACC: 0.4058
           F1score: 0.5706
         Advantage: 0.1884
               AUC: 0.2968
      P_HIGHER_AUC: 1.0000
            FMAX01: 0.3179
            FMIN01: 0.8904
            FDIF01: -0.5725
            PDIF01: -0.0000
            FMAX02: 0.3299
            FMIN02: 0.8611
            FDIF02: -0.5312
            PDIF02: -0.0000
           FMAX001: 0.2923
           FMIN001: 0.6923
           FDIF001: -0.4000
           PDIF001: 0.0000
     pred_prob_var: 0.0418


The ROC curve is alway way below the line - but ma concerned that is because the changes I introduced to stop it trying to index column4 have broken it
e.g. line 290
```
confidences[i, y_target_train[cl_pos]]#was I?
```

**Comment by jim-smith** [comment]
@simonrnss 
'too quickly' ==> in an agile fashion :)

if you don't think those attack values are way off kilter, then are we happy to merge before we e nd for the weekend?

**Review by rpreen — APPROVED** [review]

**Comment by rpreen** [comment]
pylint issues still remain...

**Comment by rpreen** [comment]
Hopefully the AIA pdf report works for you both

**Comment by simonrnss** [comment]
Fixed the linting and just checking the AIA example works. If it does, I guess I merge...have a great weekend!

**Comment by jim-smith** [comment]
@rpreen @simonrnss 
Yes, its all good.
for next week (or R1.0.1)  I'd like move some AIA metrics into the metadata the ssafemodel reports but
lets get this branch merged

**Comment by rpreen** [comment]
The metrics are dumped in the aia json file. 

Also, 
```python 
output = attack_obj.make_report()
``` 
will return the whole dict with metrics and metadata.

**Pull request merged**
