### PR TITLE
Data update

### PR DESCRIPTION
**Pull request by albacrespi**
Fix broken links to data download.

### CODE REVIEW

**Comment by yolaj-nhs** [comment]
Note: I'm still working on the code coverage/tests for this PR

**Comment by rpreen** [comment]
I notice that the openml function always onehot encodes all of the features and always label encodes the target class; is that intended? wouldn't it depend on the specific dataset fetched from openml?

**Comment by albacrespi** [comment]
Thanks for spotting this Richard, it was not intended. I think this function is better to be deleted for now as it won't work anyway.

**Review by jim-smith — APPROVED** [review]

**Review by jim-smith — CHANGES_REQUESTED** [review]
Was the decision that this till needs to have commented out the one-hot encoding of categoric .features when loading oepn-ml datasets ?

**Comment by jim-smith** [comment]
@albacrespi @rpreen 
Seems to add a set of experimental result files. Suggest these are removed and the results directory added to .gitignore so they don't get re-added

**Comment by rpreen** [comment]
FYI there is no reason to continuously merge development back into a branch just because github says so.

**Review by rpreen — APPROVED** [review]

**Review by jim-smith — APPROVED** [review]

**Pull request merged**
